import { useState } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { SupportChat } from './SupportChat'

export function AppLayout({ children, navigate }) {
  const { user, logout } = useAuth()
  const [search, setSearch] = useState(''), [menuOpen, setMenuOpen] = useState(false)
  const go = (event, path) => { event.preventDefault(); setMenuOpen(false); navigate(path) }
  const searchDocuments = (event) => { event.preventDefault(); setMenuOpen(false); navigate(`/catalogue?search=${encodeURIComponent(search)}`) }
  const logo = <a className="brand" href="/" onClick={(event) => go(event, '/')}><strong>Draworfit</strong><small>Dream And Work for it</small></a>
  const navigation = <nav className="main-nav" aria-label="Navigation principale"><a href="/catalogue" onClick={(event) => go(event, '/catalogue')}>Boutique</a>{user && <a href="/bibliotheque" onClick={(event) => go(event, '/bibliotheque')}>Bibliothèque</a>}<a href="/a-propos" onClick={(event) => go(event, '/a-propos')}>À propos</a>{!user && <a href="/connexion" onClick={(event) => go(event, '/connexion')}>Connexion</a>}{user && <a className="nav-logout" href="/" onClick={(event) => { event.preventDefault(); setMenuOpen(false); logout(); navigate('/') }}>Déconnexion</a>}</nav>
  return <div className="app-shell"><header className={`site-header ${user ? 'member-header' : 'guest-header'}`}><div className="header-row">{logo}<button className="menu-toggle" type="button" aria-label={menuOpen ? 'Fermer le menu' : 'Ouvrir le menu'} onClick={() => setMenuOpen((open) => !open)}><span>{menuOpen ? '×' : '☰'}</span><small>Menu</small></button></div><div className={`navigation-panel ${menuOpen ? 'is-open' : ''}`}>{navigation}{user && <form className="search-bar" onSubmit={searchDocuments}><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher un document…" aria-label="Rechercher un document" /><button type="submit" aria-label="Rechercher">⌕</button></form>}<div className="member-actions">{user ? <><a className="cart-button" href="/bibliotheque" onClick={(event) => go(event, '/bibliotheque')}>Bibliothèque</a><button className="user-button" type="button" onClick={() => navigate('/bibliotheque')}>{user.first_name || user.username}</button><button type="button" className="link-button" onClick={() => { logout(); navigate('/') }}>Déconnexion</button></> : <a className="button button-small" href="/inscription" onClick={(event) => go(event, '/inscription')}>Créer un compte</a>}</div></div></header><main>{children}</main><footer>© {new Date().getFullYear()} Draworfit · Dream And Work for it</footer><SupportChat navigate={navigate} /></div>
}
