# Generated by Django 5.2.8 on 2026-08-28 14:00

import django.db.models.deletion
import les_apps.licenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('platform', models.CharField(max_length=40)),
                ('public_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(default=les_apps.licenses.models.generate_activation_code, editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Prête à activer'), ('active', 'Active'), ('revoked', 'Révoquée')], default='ready', max_length=10)),
                ('code_used_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('wrapped_file_key', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='licenses.device')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='license', to='sales.orderitem')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
