# Generated by Django 5.2.8 on 2026-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chariow_product_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
