# Generated by Django 5.2.8 on 2026-09-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_chariow_product_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_published', '-created_at'], name='documents_d_is_publ_21ad2c_idx'),
        ),
    ]
