# Generated by Django 5.2.8 on 2026-09-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_sale_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='chariow', max_length=24)),
                ('delivery_id', models.CharField(max_length=120, unique=True)),
                ('event_name', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='sales.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
