import { useEffect, useState } from 'react'
import { getLicenses } from '../api/licenses'
import { useAuth } from '../contexts/AuthContext'

export function LibraryPage({ navigate }) {
  const { user } = useAuth(); const [licenses, setLicenses] = useState([]); const [state, setState] = useState('loading')
  useEffect(() => { if (!user) { setState('anonymous'); return } getLicenses().then((data) => { setLicenses(data.results || data); setState('ready') }).catch(() => setState('error')) }, [user])
  if (state === 'anonymous') return <section className="page-message"><p>Connectez-vous pour voir vos achats.</p><button className="button" onClick={() => navigate('/connexion')}>Connexion</button></section>
  return <section className="catalog-page"><p className="eyebrow">MA BIBLIOTHÈQUE</p><h1>Mes documents achetés</h1>{state === 'loading' && <p className="page-message">Chargement…</p>}{state === 'error' && <p className="page-message error-message">Impossible de charger vos achats.</p>}{state === 'ready' && !licenses.length && <p className="page-message">Vous n’avez pas encore de document disponible.</p>}{state === 'ready' && licenses.length > 0 && <div className="document-grid">{licenses.map((license) => <article className="document-card" key={license.id}><div className="cover-placeholder">PDF</div><div className="document-card-content"><p className="document-category">{license.status === 'ready' ? 'À activer' : license.status === 'active' ? 'Activé' : 'Révoqué'}</p><h2>{license.document.title}</h2><p>{license.device ? `Appareil : ${license.device.name}` : 'Ce document n’est pas encore lié à un appareil.'}</p>{license.status === 'ready' && <><code className="activation-code">{license.activation_code}</code><button className="text-action" onClick={() => navigate('/activation')}>Activer maintenant</button></>}{license.status === 'active' && <button className="button" onClick={() => navigate(`/lecture/${license.id}`)}>Lire le document</button>}</div></article>)}</div>}</section>
}
