import { useEffect, useState } from 'react'
import { adminCreate, adminDelete, adminList, adminUpdate } from '../api/superadmin'
import { getProfile, login } from '../api/auth'
import { useAuth } from '../contexts/AuthContext'
import './SuperAdminPage.css'

const sections = { documents: { label: 'Documents', columns: ['title', 'category_name', 'price', 'currency', 'is_published'], form: ['title', 'description', 'category', 'price', 'currency', 'chariow_snap_html', 'is_published'], canCreate: true }, categories: { label: 'Catégories', columns: ['name', 'slug'], form: ['name'], canCreate: true }, users: { label: 'Utilisateurs', columns: ['username', 'email', 'phone_number', 'university', 'country_of_origin', 'is_active'], form: ['username', 'email', 'password', 'first_name', 'last_name', 'phone_number', 'university', 'country_of_origin', 'is_active', 'is_staff', 'is_superuser'], canCreate: true }, orders: { label: 'Commandes', columns: ['id', 'customer_name', 'status', 'total_amount', 'currency', 'payment_provider', 'provider_sale_id', 'items_count'], form: ['status'] }, licenses: { label: 'Licences', columns: ['id', 'document_title', 'status', 'activation_code', 'activated_at'], form: ['status'] }, devices: { label: 'Appareils', columns: ['name', 'platform', 'installation_id', 'last_seen_at'], form: [] }, 'order-items': { label: 'Lignes de commande', columns: ['id', 'order', 'document', 'title', 'unit_price'], form: [] } }
const labels = { is_published: 'Publié', is_active: 'Actif', is_staff: 'Administrateur', category: 'Catégorie', country_of_origin: 'Pays d’origine', phone_number: 'Téléphone', customer_name: 'Client', total_amount: 'Montant', items_count: 'Articles', activation_code: 'Code d’activation', document_title: 'Document', last_seen_at: 'Dernière activité' }
const label = (value) => labels[value] || value.replaceAll('_', ' ')
const show = (value) => value === null || value === undefined || value === '' ? '—' : typeof value === 'boolean' ? (value ? 'Oui' : 'Non') : String(value)
const defaults = () => ({ currency: 'XOF', is_published: false, is_active: true })

function SuperAdminLogin() {
  const { setUser } = useAuth(); const [username, setUsername] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const submit = async (event) => { event.preventDefault(); setError(''); setBusy(true); try { await login(username, password); const profile = await getProfile(); if (!profile.is_staff) { localStorage.removeItem('access_token'); localStorage.removeItem('refresh_token'); throw new Error() } setUser(profile) } catch { setError('Identifiants administrateur incorrects.') } finally { setBusy(false) } }
  return <section className="auth-page"><div className="auth-card"><p className="eyebrow">DRAWORFIT · SUPERADMIN</p><h1>Connexion administrateur</h1><p className="form-subtitle">Accédez à la gestion des documents et des commandes.</p>{error && <p className="form-error">{error}</p>}<form onSubmit={submit}><label>Nom d’utilisateur<input required value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" /></label><label>Mot de passe<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" /></label><button className="button" disabled={busy}>{busy ? 'Connexion…' : 'Se connecter'}</button></form></div></section>
}

export function SuperAdminPage({ navigate }) {
  const { user, isLoading, logout } = useAuth(); const [active, setActive] = useState('documents'), [rows, setRows] = useState([]), [categories, setCategories] = useState([]), [dashboard, setDashboard] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [editing, setEditing] = useState(null), [form, setForm] = useState(defaults())
  const load = async () => { setLoading(true); setError(''); try { const requests = [adminList(active), adminList('dashboard')]; if (active === 'documents') requests.push(adminList('categories')); const [list, overview, categoryList] = await Promise.all(requests); setRows(list.results || list); setDashboard(overview); if (categoryList) setCategories(categoryList.results || categoryList); setEditing(null); setForm(defaults()) } catch { setError("Impossible de charger l’administration.") } finally { setLoading(false) } }
  useEffect(() => { if (user?.is_staff) load() }, [active, user])
  useEffect(() => { if (!editing) document.querySelector('.admin-form')?.reset() }, [rows, editing])
  if (isLoading) return <p className="page-message">Chargement…</p>
  if (!user) return <SuperAdminLogin />
  if (!user?.is_staff) return <section className="page-message"><h1>Accès refusé</h1><button className="button" onClick={() => navigate('/')}>Retour au site</button></section>
  const config = sections[active], set = (field, value) => setForm({ ...form, [field]: value })
  const save = async (event) => { event.preventDefault(); setError(''); try { let body; if (active === 'documents') { body = new FormData(); config.form.forEach((field) => { if (form[field] !== undefined && form[field] !== null) body.append(field, form[field]) }); if (form.cover) body.append('cover_image', form.cover); form.files?.forEach((file) => body.append('encrypted_files', file)) } else body = JSON.stringify(config.form.reduce((data, field) => ({ ...data, [field]: form[field] ?? '' }), {})); editing ? await adminUpdate(active, editing.id, body) : await adminCreate(active, body); await load() } catch { setError("L’enregistrement a échoué. Vérifiez les champs obligatoires.") } }
  const input = (field) => { if (field === 'description' || field === 'chariow_snap_html') return <label key={field}>{field === 'chariow_snap_html' ? 'Code HTML Snap Chariow' : label(field)}<textarea value={form[field] || ''} onChange={(e) => set(field, e.target.value)} placeholder={field === 'chariow_snap_html' ? '<div id="chariow-widget" ...></div>' : undefined} /></label>; if (['is_published', 'is_active', 'is_staff', 'is_superuser'].includes(field)) return <label className="admin-check" key={field}><input type="checkbox" checked={!!form[field]} onChange={(e) => set(field, e.target.checked)} /> {label(field)}</label>; if (field === 'category') return <label key={field}>{label(field)}<select required value={form[field] || ''} onChange={(e) => set(field, e.target.value || null)}><option value="">Choisir une catégorie</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label>; if (field === 'status') return <label key={field}>Statut<select value={form.status || 'pending'} onChange={(e) => set(field, e.target.value)}>{['pending', 'paid', 'cancelled', 'ready', 'active', 'revoked'].map((status) => <option value={status} key={status}>{status}</option>)}</select></label>; return <label key={field}>{label(field)}<input type={field === 'price' ? 'number' : field === 'password' ? 'password' : 'text'} step={field === 'price' ? '0.01' : undefined} value={form[field] || ''} onChange={(e) => set(field, e.target.value)} /></label> }
  return <div className="superadmin-shell"><aside className="superadmin-side"><strong>DRAWORFIT</strong><small>SUPERADMIN</small>{Object.entries(sections).map(([key, item]) => <button key={key} className={active === key ? 'active' : ''} onClick={() => setActive(key)}>{item.label}</button>)}<button className="admin-exit" onClick={() => { logout(); navigate('/') }}>Déconnexion</button></aside><main className="superadmin-main"><header><div><p>ADMINISTRATION</p><h1>{config.label}</h1></div>{config.canCreate && <button className="button" onClick={() => { setEditing(null); setForm(defaults()) }}>Ajouter</button>}</header>{dashboard && <div className="admin-stats">{Object.entries(dashboard).map(([key, value]) => <div key={key}><strong>{value}</strong><span>{label(key)}</span></div>)}</div>}{error && <p className="form-error">{error}</p>}<section className="admin-content">{config.form.length > 0 && <form className="admin-form" onSubmit={save}><h2>{editing ? 'Modifier' : 'Nouveau'}</h2>{config.form.map(input)}{active === 'documents' && <><label>Image de couverture<input type="file" accept="image/*" onChange={(e) => set('cover', e.target.files[0])} /></label><label>Documents PDF protégés du lot<input type="file" accept="application/pdf" multiple onChange={(e) => set('files', Array.from(e.target.files))} /><small>Ajoutez autant de PDF que nécessaire : l’acheteur achète et active ce seul lot.</small></label></>}<div><button className="button">Enregistrer</button>{editing && <button type="button" className="link-button" onClick={() => { setEditing(null); setForm(defaults()) }}>Annuler</button>}</div></form>}<div className="admin-table-wrap">{loading ? <p>Chargement…</p> : <table><thead><tr>{config.columns.map((column) => <th key={column}>{label(column)}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{config.columns.map((column) => <td key={column}>{show(row[column])}</td>)}<td><button className="text-action" onClick={() => { setEditing(row); setForm({ ...row }) }}>Modifier</button><button className="text-action danger" onClick={async () => { if (window.confirm('Supprimer cet élément ?')) { try { await adminDelete(active, row.id); await load() } catch { setError('Suppression impossible.') } } }}>Supprimer</button></td></tr>)}</tbody></table>}</div></section></main></div>
}
